### ISSUE TITLE
Materials with alpha do not display properly in SSS

### ISSUE THREAD

**Issue by anonRipper** [Infused-Doggo/ShaderFarc#1]
![SSS](https://github.com/Infused-Doggo/ShaderFarc/assets/107647567/fc7f9964-21fa-45dd-a097-07c27561b50e)
I found setting ALPHA_TEST_DEF to 1 in SSS/+/- Header.fxsub can solve this problem.
![SSS2](https://github.com/Infused-Doggo/ShaderFarc/assets/107647567/d7c9b9c4-df1b-4d55-a3b0-bdf21bc35167)

**Comment by Infused-Doggo** [comment]
Oh yeah, now I just noticed about this.
![image](https://github.com/Infused-Doggo/ShaderFarc/assets/92472738/2775a40b-d3e0-46b9-8a5a-3d15c2f8fac6)

Didn't check back the alpha clip was disabled

![image](https://github.com/Infused-Doggo/ShaderFarc/assets/92472738/4412fdd7-1d76-4e66-8770-90b70c0788dd)


![image](https://github.com/Infused-Doggo/ShaderFarc/assets/92472738/5b08e035-4efb-4ac5-bf20-73f332a38e50)

**Comment by Infused-Doggo** [comment]
Punch_through is now set at 1
